blkbrds/intern16-practice

- .gitignore
> Feature - Add gitignore

- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project.xcodeproj/project.pbxproj
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/AppDelegate.swift
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/Assets.xcassets/AppIcon.appiconset/Contents.json
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/Assets.xcassets/Contents.json
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/Info.plist
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/Preview Content/Preview Assets.xcassets/Contents.json
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/SceneDelegate.swift
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/ViewController.swift
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1project/ViewController.xib
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1projectTests/Hien_nguyen_Baitap1projectTests.swift
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1projectTests/Info.plist
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1projectUITests/Hien_nguyen_Baitap1projectUITests.swift
- 01_GioiThieu/Hien.Nguyen4/Hien.nguyen.Baitap1project/Hien.nguyen.Baitap1projectUITests/Info.plist
Bài tập 1 change color
Project không sử dụng Storyboard
Fix comment và tạo PR lại 
Please help me review this!
> HienNguyen4_Bài tập 1_Change color

- 01_GioiThieu/HuyenNguyen/Ex01.xcodeproj/project.pbxproj
- 01_GioiThieu/HuyenNguyen/Ex01.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 01_GioiThieu/HuyenNguyen/Ex01.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 01_GioiThieu/HuyenNguyen/Ex01/AppDelegate.swift
- 01_GioiThieu/HuyenNguyen/Ex01/Assets.xcassets/AppIcon.appiconset/Contents.json
- 01_GioiThieu/HuyenNguyen/Ex01/Assets.xcassets/Contents.json
- 01_GioiThieu/HuyenNguyen/Ex01/Base.lproj/LaunchScreen.storyboard
- 01_GioiThieu/HuyenNguyen/Ex01/Base.lproj/Main.storyboard
- 01_GioiThieu/HuyenNguyen/Ex01/Info.plist
- 01_GioiThieu/HuyenNguyen/Ex01/MyViewController.swift
- 01_GioiThieu/HuyenNguyen/Ex01/MyViewController.xib
- 01_GioiThieu/HuyenNguyen/Ex01/SceneDelegate.swift
- 01_GioiThieu/HuyenNguyen/Ex01/ViewController.swift
> HuyenNguyen - Giới thiệu - Bài tập 1

- 02_SwiftBasic/HaVan/BaiTap1.playground/Contents.swift
- 02_SwiftBasic/HaVan/BaiTap2.playground/Contents.swift
- 02_SwiftBasic/HaVan/BaiTap3.playground/Contents.swift
- 02_SwiftBasic/HaVan/BaiTap4.playground/Contents.swift
- 02_SwiftBasic/HaVan/BaiTap5.playground/Contents.swift
- 02_SwiftBasic/HaVan/BaiTap6.playground/Contents.swift
- 02_SwiftBasic/HaVan/BaiTap7.playground/Contents.swift
Đã fix xong convention của bài 1 đến 7 phần swift basic
> HaVan - Swift Basic - Fix convention

- 03_SwiftOOP/HUYENNGUYEN/Baitap3.1.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.1.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.10.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.10.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.2.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.2.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.3.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.3.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.4.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.4.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.5.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.5.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.6.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.6.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.7.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.7.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.8.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.8.playground/contents.xcplayground
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.9.playground/Contents.swift
- 03_SwiftOOP/HUYENNGUYEN/Baitap3.9.playground/contents.xcplayground
- Tính phân số
- Tính chu vi đa giác
- Tính diện tích tam giác kế thừa từ lớp Đa giác
- Kiểm tra cạnh theo Pitago
- Ngăn xếp Stack
- Hình 2 chiều, 3 chiều
- Danh sách học sinh
- Ngày tháng năm
- Mảng 1 chiều
- Tổng n số nguyên
> HUYENNGUYEN - OOP Swift - Bài tập 1->10

- 03_SwiftOOP/HaVan/BaiTap1.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap1.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap10.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap10.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap2Va3.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap2Va3.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap4.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap4.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap5.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap5.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap6.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap6.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap7.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap7.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap8.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap8.playground/contents.xcplayground
- 03_SwiftOOP/HaVan/BaiTap9.playground/Contents.swift
- 03_SwiftOOP/HaVan/BaiTap9.playground/contents.xcplayground
- 04_View/HaVan/BaiTapView/BaiTapView.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Bài 1: Phân số
Bài 2: Đa giác
Bài 3: Tam giác kế thừa đa giác
Bài 4: Tam giác pytago
Bài 5: Stack
Bài 6: Hình học 2 chiều, 3 chiều
Bài 7: Danh sách học sinh
Bài 8: Xử lý ngày tháng năm
Bài 9: Class mảng số nguyên
Bài 10: Tính tổng dãy số 1 đến n
> HaVan - Bài tập OOP - Bài 1 đến 10

- 03_SwiftOOP/HOANGUYEN/baitap03/baitap01.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap01.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap02+03.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap02+03.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap04.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap04.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap05.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap05.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap06.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap06.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap07.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap07.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap08.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap08.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap09.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap09.playground/contents.xcplayground
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap10.playground/Contents.swift
- 03_SwiftOOP/HOANGUYEN/baitap03/baitap10.playground/contents.xcplayground
> HOANGUYEN - Phần Swift OOP - Bài 1-10

- 02_SwiftBasic/HIENNGUYEN4:Baitap2_lan1/MyPlayground.playground/Contents.swift
HienNguyen4 đã tạo PRL phần bài tập BasicSwift.
Tuy nhiên, phần PR này chỉ có 2 bài tập:
Bài tập 1: Tính diện tích, thể tích hình cầu
Bài tập 2: Hoán đổi ví trị random mảng 0,1,2....->9
Nhờ Reviewers xem lại giúp nhé.
> HienNguyen - Basic Swift - Bài tập số 1 & 7 (lần 1) 

- 03_SwiftOOP/KHANHPN/Bài 1.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 1.playground/contents.xcplayground
- 03_SwiftOOP/KHANHPN/Bài 10.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 10.playground/contents.xcplayground
- 03_SwiftOOP/KHANHPN/Bài 2+3.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 2+3.playground/contents.xcplayground
- 03_SwiftOOP/KHANHPN/Bài 4.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 4.playground/contents.xcplayground
- 03_SwiftOOP/KHANHPN/Bài 5.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 5.playground/contents.xcplayground
- 03_SwiftOOP/KHANHPN/Bài 6.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 6.playground/contents.xcplayground
- 03_SwiftOOP/KHANHPN/Bài 8.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 8.playground/contents.xcplayground
- 03_SwiftOOP/KHANHPN/Bài 9.playground/Contents.swift
- 03_SwiftOOP/KHANHPN/Bài 9.playground/contents.xcplayground
Hoàn thành 1 số bài tập phần OOP.
Đang làm nốt những bài tiếp theo ạ...
> Khanh Phan - Bài tập phần Swift OOP

- 02_SwiftBasic/HuyenNguyen/Baitap2.1.playground/Contents.swift
- 02_SwiftBasic/HuyenNguyen/Baitap2.1.playground/contents.xcplayground
- 02_SwiftBasic/HuyenNguyen/Baitap2.2.playground/Contents.swift
- 02_SwiftBasic/HuyenNguyen/Baitap2.2.playground/contents.xcplayground
- 02_SwiftBasic/HuyenNguyen/Baitap2.3.playground/Contents.swift
- 02_SwiftBasic/HuyenNguyen/Baitap2.3.playground/contents.xcplayground
- 02_SwiftBasic/HuyenNguyen/Baitap2.4.playground/Contents.swift
- 02_SwiftBasic/HuyenNguyen/Baitap2.4.playground/contents.xcplayground
- 02_SwiftBasic/HuyenNguyen/Baitap2.5.playground/Contents.swift
- 02_SwiftBasic/HuyenNguyen/Baitap2.5.playground/contents.xcplayground
- 02_SwiftBasic/HuyenNguyen/Baitap2.6.playground/Contents.swift
- 02_SwiftBasic/HuyenNguyen/Baitap2.6.playground/contents.xcplayground
- 02_SwiftBasic/HuyenNguyen/Baitap2.7.playground/Contents.swift
- 02_SwiftBasic/HuyenNguyen/Baitap2.7.playground/contents.xcplayground
Fixed comment code exercise 06
> HUYENNGUYEN - Bài tập Swift Basic - 7 bài tập

- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing.xcodeproj/project.pbxproj
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/AppDelegate.swift
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/Assets.xcassets/AppIcon.appiconset/Contents.json
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/Assets.xcassets/Contents.json
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/BaiTap1/BaiTap1ViewController.swift
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/BaiTap1/BaiTap1ViewController.xib
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/BaiTap1/ColumnChartView.swift
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/BaiTap2/BaiTap2View.swift
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/BaiTap2/BaiTap2ViewController.swift
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/Base.lproj/LaunchScreen.storyboard
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/Info.plist
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/SceneDelegate.swift
- 06_Drawing/MINHNGUYEN T/BaiTapDrawing/BaiTapDrawing/ViewController.swift
> MinhNguyen - Phan Drawing - Bai Tap 1-2

- 06_Drawing/BaiTapDraw/BaiTapDraw.xcodeproj/project.pbxproj
- 06_Drawing/BaiTapDraw/BaiTapDraw.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 06_Drawing/BaiTapDraw/BaiTapDraw.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 06_Drawing/BaiTapDraw/BaiTapDraw/AppDelegate.swift
- 06_Drawing/BaiTapDraw/BaiTapDraw/Assets.xcassets/AppIcon.appiconset/Contents.json
- 06_Drawing/BaiTapDraw/BaiTapDraw/Assets.xcassets/Contents.json
- 06_Drawing/BaiTapDraw/BaiTapDraw/BaiTap01/BaiTap01.swift
- 06_Drawing/BaiTapDraw/BaiTapDraw/BaiTap01/ChartView.swift
- 06_Drawing/BaiTapDraw/BaiTapDraw/BaiTap01/ChartView.xib
- 06_Drawing/BaiTapDraw/BaiTapDraw/BaiTap02/BaiTap02.swift
- 06_Drawing/BaiTapDraw/BaiTapDraw/BaiTap02/CircleCustom.swift
- 06_Drawing/BaiTapDraw/BaiTapDraw/BaiTap02/CircleCustom.xib
- 06_Drawing/BaiTapDraw/BaiTapDraw/BaiTap02/CircleCustomView.swift
- 06_Drawing/BaiTapDraw/BaiTapDraw/Info.plist
- 06_Drawing/BaiTapDraw/BaiTapDraw/SceneDelegate.swift
> TrinNguyen - Phần Draw - Bài 1,2

- 06_Drawing/HUYENNGUYEN/Drawing.xcodeproj/project.pbxproj
- 06_Drawing/HUYENNGUYEN/Drawing.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 06_Drawing/HUYENNGUYEN/Drawing.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 06_Drawing/HUYENNGUYEN/Drawing/AppDelegate.swift
- 06_Drawing/HUYENNGUYEN/Drawing/Assets.xcassets/AppIcon.appiconset/Contents.json
- 06_Drawing/HUYENNGUYEN/Drawing/Assets.xcassets/Contents.json
- 06_Drawing/HUYENNGUYEN/Drawing/Bai01/Bai01.swift
- 06_Drawing/HUYENNGUYEN/Drawing/Bai01/Bai01View.swift
- 06_Drawing/HUYENNGUYEN/Drawing/Bai01/Bai01ViewController.swift
- 06_Drawing/HUYENNGUYEN/Drawing/Bai02/Bai02.swift
- 06_Drawing/HUYENNGUYEN/Drawing/Bai02/Bai02View.swift
- 06_Drawing/HUYENNGUYEN/Drawing/Bai02/Bai02ViewController.swift
- 06_Drawing/HUYENNGUYEN/Drawing/Base.lproj/LaunchScreen.storyboard
- 06_Drawing/HUYENNGUYEN/Drawing/Base.lproj/Main.storyboard
- 06_Drawing/HUYENNGUYEN/Drawing/Info.plist
- 06_Drawing/HUYENNGUYEN/Drawing/SceneDelegate.swift
- 06_Drawing/HUYENNGUYEN/Drawing/ViewController.swift
> HUYENNGUYEN - Phần Drawing - Bài 1 và 2

- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC.xcodeproj/project.pbxproj
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/App Delegate/AppDelegate.swift
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/App Delegate/SceneDelegate.swift
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Base.lproj/LaunchScreen.storyboard
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Controllers/BaitapMVCViewController.swift
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Info.plist
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Models/Calculator.swift
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Models/RoundButton.swift
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Resources/Assets.xcassets/Contents.json
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Views/CalculatorView.swift
- 08_MVC/TamNguyen/BaitapMVC/BaitapMVC/Views/CalculatorView.xib
> TamNguyen - Bai tap 8 - MVC

- 08_MVC/BaiTapMVc/BaiTapMVC.xcodeproj/project.pbxproj
- 08_MVC/BaiTapMVc/BaiTapMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 08_MVC/BaiTapMVc/BaiTapMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 08_MVC/BaiTapMVc/BaiTapMVC/AppDelegate/AppDelegate.swift
- 08_MVC/BaiTapMVc/BaiTapMVC/AppDelegate/SceneDelegate.swift
- 08_MVC/BaiTapMVc/BaiTapMVC/Assets.xcassets/AppIcon.appiconset/Contents.json
- 08_MVC/BaiTapMVc/BaiTapMVC/Assets.xcassets/Contents.json
- 08_MVC/BaiTapMVc/BaiTapMVC/Controllers/CalculatorViewController.swift
- 08_MVC/BaiTapMVc/BaiTapMVC/Info.plist
- 08_MVC/BaiTapMVc/BaiTapMVC/Models/Calculator.swift
- 08_MVC/BaiTapMVc/BaiTapMVC/Views/CalculatorView.xib
> TrinNguyen- Phần MVC - Bài 1 

- 08_MVC/HUYENNGUYEN/MVC/MVC.xcodeproj/project.pbxproj
- 08_MVC/HUYENNGUYEN/MVC/MVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 08_MVC/HUYENNGUYEN/MVC/MVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 08_MVC/HUYENNGUYEN/MVC/MVC/AppDelegate.swift
- 08_MVC/HUYENNGUYEN/MVC/MVC/Assets.xcassets/AppIcon.appiconset/Contents.json
- 08_MVC/HUYENNGUYEN/MVC/MVC/Assets.xcassets/Contents.json
- 08_MVC/HUYENNGUYEN/MVC/MVC/Base.lproj/LaunchScreen.storyboard
- 08_MVC/HUYENNGUYEN/MVC/MVC/Base.lproj/Main.storyboard
- 08_MVC/HUYENNGUYEN/MVC/MVC/CalculatorBrain.swift
- 08_MVC/HUYENNGUYEN/MVC/MVC/CalculatorViewController.swift
- 08_MVC/HUYENNGUYEN/MVC/MVC/CalculatorViewController.xib
- 08_MVC/HUYENNGUYEN/MVC/MVC/Info.plist
- 08_MVC/HUYENNGUYEN/MVC/MVC/SceneDelegate.swift
- 08_MVC/HUYENNGUYEN/MVC/MVC/ViewController.swift
- 08_MVC/HUYENNGUYEN/MyPlayground.playground/Contents.swift
- 08_MVC/HUYENNGUYEN/MyPlayground.playground/contents.xcplayground
> HUYENNGUYEN - Phần MVC

- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC.xcodeproj/project.pbxproj
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/AppDelegate.swift
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Assets.xcassets/AppIcon.appiconset/Contents.json
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Assets.xcassets/Contents.json
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Base.lproj/LaunchScreen.storyboard
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Controller/CalculationViewController.swift
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Controller/CalculationViewController.xib
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Info.plist
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Model/Calculator.swift
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/Model/CalculatorFactory.swift
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/SceneDelegate.swift
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/View/CalculationView.swift
- 08_MVC/HaVan/BaiTapMVC/BaiTapMVC/View/CalculationView.xib
> HaVan - Phần MVC - Bài 1

- 10_Protocol/HaVan/BaiTap1.playground/Contents.swift
- 10_Protocol/HaVan/BaiTap1.playground/contents.xcplayground
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol.xcodeproj/project.pbxproj
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/AppDelegate.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/Assets.xcassets/AppIcon.appiconset/Contents.json
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/Assets.xcassets/Contents.json
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/BaseViewController.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/BaseViewController.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Diadiem/DiaDiemViewController.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Diadiem/DiaDiemViewController.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Huyen/HuyenViewController.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Huyen/HuyenViewController.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Mien/MienViewController.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Mien/MienViewController.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Tinh/TinhViewController.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap3/Tinh/TinhViewController.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap4/BaiTap4ViewController.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap4/BaiTap4ViewController.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap4/TenTinhThanh.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap5/BaiTap5ViewController.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap5/BaiTap5ViewController.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap5/Calculation.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap5/CalculatorCustomView.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap5/CalculatorCustomView.xib
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/BaiTap5/CalculatorState.swift
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/Base.lproj/LaunchScreen.storyboard
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/Info.plist
- 10_Protocol/HaVan/BaiTapProtocol/BaiTapProtocol/SceneDelegate.swift
> HAVAN - Phần Protocol - Bài tập 1 -> 5

- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC.xcodeproj/project.pbxproj
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/AppDelegate.swift
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/Assets.xcassets/AppIcon.appiconset/Contents.json
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/Assets.xcassets/Contents.json
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/Base.lproj/LaunchScreen.storyboard
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/Controller/HomeViewController.swift
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/Info.plist
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/Model/Caculator.swift
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/Model/OperatorAction.swift
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/SceneDelegate.swift
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/View/CaculatorUIView.swift
- 08_MVC/MinhNguyen T/BaiTapMVC/BaiTapMVC/View/CaculatorUIView.xib
> MinhNguyen - Phần MVC -  Bài Tập 1

- 10_Protocol/BaiTapProtocol/BaiTap01.playground/Contents.swift
- 10_Protocol/BaiTapProtocol/BaiTap01.playground/contents.xcplayground
- 10_Protocol/BaiTapProtocol/BaiTapProtocol.xcodeproj/project.pbxproj
- 10_Protocol/BaiTapProtocol/BaiTapProtocol.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- 10_Protocol/BaiTapProtocol/BaiTapProtocol.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/AppDelegate.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/Assets.xcassets/AppIcon.appiconset/Contents.json
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/Assets.xcassets/Contents.json
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/DistrictViewController.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/DistrictViewController.xib
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/LocationViewController.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/LocationViewController.xib
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/ProvinceViewController.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/ProvinceViewController.xib
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/RegionViewController.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap03/RegionViewController.xib
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap04/SeachViewController.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap04/SeachViewController.xib
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap05/CalculateViewController.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap05/CalculateViewController.xib
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap05/Calculator.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap05/CustomViewCalculate.swift
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/BaiTap05/CustomViewCalculate.xib
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/Info.plist
- 10_Protocol/BaiTapProtocol/BaiTapProtocol/SceneDelegate.swift
> TRINNGUYENX - Protocol - BaiTap 1,3,4,5
